### ISSUE TITLE
Finding record fails if entity has non-string-attribute valid for quickfind

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MsCrmTools.AccessChecker#1]
In this case I think it is an optionset.

![image](https://cloud.githubusercontent.com/assets/2572253/17775324/0940cec4-6558-11e6-9be5-9a493df56e3e.png)

**Comment by MscrmTools** [comment]
I just don't know how CRM handle this problem since you can put any attribute as quick search column but some of them clearly cannot be used when searching

**Comment by fleurya** [comment]
I have the same issue. There is a lookup field (Contact) available as a search field in the quick find. 
And I receive error:

An error occured: An exception System.FormatException was thrown while trying to convert input value '%' to attribute 'opportunity.dp_resellercontact'. Expected type of attribute value: System.Guid. Exception raised: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

**Comment by MscrmTools** [comment]
Ok, I found a way to handle this... stay tuned in Plugins Store to get the new version
