### ISSUE TITLE
Object ID search no longer working?

### ISSUE THREAD

**Issue by mdhauck** [MscrmTools/MsCrmTools.AccessChecker#13]
Is it just me or does the search for an object id no longer work (wondering if it is relevance search related)?  Doesn't matter what table I try, wildcards or not, I get an error (see below)

![2021-09-13_16-44-00](https://user-images.githubusercontent.com/46872221/133153749-b4744d62-dc88-40e4-a69e-4e052485708a.png)

**Comment by MscrmTools** [comment]
@mdhauck Can you check with this version?
[MsCrmTools.AccessChecker.zip](https://github.com/MscrmTools/MsCrmTools.AccessChecker/files/7159587/MsCrmTools.AccessChecker.zip)

**Comment by mdhauck** [comment]
So just to ensure I did it correctly, I know have version 1.2021.9.5 (vs 4) after adding that DLL into my directory.  IF that is correct, unfortunately it did not solve the issue (same error)?

Thanks for the quick reply!!!

**Comment by MscrmTools** [comment]
Would it be possible for you to extract the fetchxml of your quick find view for contacts?

**Comment by MscrmTools** [comment]
@mdhauck is that really the exact same issue? normally, it shouldn't be exactly the same since I removed the method that failed.
Can you share a screenshot?

**Comment by mdhauck** [comment]
Contact XML attached BUT just so you know this is not specific to a table or even customer or environment.  I can duplicate pretty much any environment I have access to?


From: MscrmTools ***@***.***>
Date: Tuesday, September 14, 2021 at 11:27 AM
To: MscrmTools/MsCrmTools.AccessChecker ***@***.***>
Cc: mdhauck ***@***.***>, Mention ***@***.***>
Subject: Re: [MscrmTools/MsCrmTools.AccessChecker] Object ID search no longer working? (#13)

Would it be possible for you to extract the fetchxml of your quick find view for contacts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMscrmTools%2FMsCrmTools.AccessChecker%2Fissues%2F13%23issuecomment-919260713&data=04%7C01%7C%7Cba31d91f77ea4204f89508d977943658%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672300708012633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ljsgu8VIYKqspAQfbHeJd3RcEDzgBTR%2FW6wSCvpzXSE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALFTNHML2QP6LMHWFRGNA5LUB5SXLANCNFSM5D6U7BEQ&data=04%7C01%7C%7Cba31d91f77ea4204f89508d977943658%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672300708022601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S4z3IKnkM9wzXy%2FpGoIpFFC0aF6Sy813V%2FxVn8AB3G4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cba31d91f77ea4204f89508d977943658%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672300708022601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cXH9dJyuM2twDIdIGUua8BN0ygUdkjA2mgQs9I%2Fu1%2B4%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cba31d91f77ea4204f89508d977943658%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672300708032549%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xTKdhAoPVFsJw4ZRnCjPO1pDo9S3J7PcZk6ek%2Fpk%2BH8%3D&reserved=0>.

**Comment by mdhauck** [comment]
3 attachments
1st environment Accounts
1st environment contacts
2nd environment contacts



From: MscrmTools ***@***.***>
Date: Tuesday, September 14, 2021 at 11:36 AM
To: MscrmTools/MsCrmTools.AccessChecker ***@***.***>
Cc: mdhauck ***@***.***>, Mention ***@***.***>
Subject: Re: [MscrmTools/MsCrmTools.AccessChecker] Object ID search no longer working? (#13)

@mdhauck<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmdhauck&data=04%7C01%7C%7C4dc0197683874672254a08d977956326%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672305764819242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6%2FdGpuM747QRS3WgnyUL5MihGFYJKJmH754g%2Bn6FtqY%3D&reserved=0> is that really the exact same issue? normally, it shouldn't be exactly the same since I removed the method that failed.
Can you share a screenshot?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMscrmTools%2FMsCrmTools.AccessChecker%2Fissues%2F13%23issuecomment-919268313&data=04%7C01%7C%7C4dc0197683874672254a08d977956326%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672305764829200%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iPY7VkaSpfEX47F9gLgDrMaaQas9F9hBOzkLjtvVwoE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALFTNHKLXEG3HN6GEHIIGULUB5TW3ANCNFSM5D6U7BEQ&data=04%7C01%7C%7C4dc0197683874672254a08d977956326%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672305764829200%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yblwcowfIkzM6lYv%2FAfLI8yhLLjfjdQrTCwzROxOXMY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4dc0197683874672254a08d977956326%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672305764839152%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QL9g4M6TpT71Dy%2F%2Fe9a6rjskZWzOyIjPeRoUGPrYJSw%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C4dc0197683874672254a08d977956326%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637672305764839152%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M0E622thCN2IyMXNt%2F3E8m0RTaIdkF2KDJjn3ZJtB%2BQ%3D&reserved=0>.

**Comment by MscrmTools** [comment]
It does not work by email for attachments. Can you log in Github to attach files?

I do not reproduce on my env, that's why I am asking

**Comment by mdhauck** [comment]
Here are files.
![Env 1 Accounts](https://user-images.githubusercontent.com/46872221/133330266-10954c53-8840-49ba-b77a-b6a9178f3f5d.png)
![Env 1 Contacts](https://user-images.githubusercontent.com/46872221/133330268-5ba06cba-983e-4635-a8af-750d3c398ab2.png)
![Env 2 Contacts](https://user-images.githubusercontent.com/46872221/133330269-f2e3f953-05d0-47c7-acd8-a9799c5bc883.png)

**Comment by MscrmTools** [comment]
Ok, this one should be better
[MsCrmTools.AccessChecker.zip](https://github.com/MscrmTools/MsCrmTools.AccessChecker/files/7167946/MsCrmTools.AccessChecker.zip)

**Comment by mdhauck** [comment]
That did the trick (THANK YOU!).  I can't figure out limitation but I still have one environment where it only works part of the time.  I'm confident the issue is the table size/record count because it works on my smaller tables in that environment but NOT the big ones.

**Comment by MscrmTools** [comment]
Thank you for the feedback. The updated version is going to be available soon in Tool Library
