### ISSUE TITLE
CRM on premise: Cannot utillize WebAPI for this request

### ISSUE THREAD

**Issue by alen1979** [MscrmTools/MsCrmTools.AccessChecker#14]
When using the latest version of Access Checker against an on a CRM on premise V9 instance getting this error now:

![AccessCheckerIssue](https://user-images.githubusercontent.com/17340036/139006753-a0134d37-aa93-41fa-8ce7-b7f304a67d76.jpg)

Is CRM on premise still supported ? I was using access checker for years now

**Comment by MscrmTools** [comment]
@LinkeD365 can you help here?

**Comment by MscrmTools** [comment]
@alen1979, can you test with this version?
[MsCrmTools.AccessChecker.zip](https://github.com/MscrmTools/MsCrmTools.AccessChecker/files/8132803/MsCrmTools.AccessChecker.zip)

**Comment by MscrmTools** [comment]
Should be fixed on latest version
