### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by sumitd1301** [MscrmTools/MsCrmTools.AccessChecker#15]
Recently I observed that this tool is not working and giving the following error 
<img width="915" alt="3ljHv4DqYj" src="https://user-images.githubusercontent.com/38563206/151136738-787792da-08d3-4915-b64e-4fedb8be8f7e.png">

**Comment by MscrmTools** [comment]
Hi @sumitd1301, can you test this version?
[MsCrmTools.AccessChecker.zip](https://github.com/MscrmTools/MsCrmTools.AccessChecker/files/8132849/MsCrmTools.AccessChecker.zip)

**Comment by darshSWL** [comment]
@MscrmTools I have the same problem and the version in your comment fixes it.

**Comment by MscrmTools** [comment]
@darshSWL, thank you very much. I will release a new version then
