### ISSUE TITLE
Bug: Not possible to run on entities of type organization

### ISSUE THREAD

**Issue by daggen** [MscrmTools/MsCrmTools.AccessChecker#2]
It is not possible to get the information if the entity is of ownership type organization. It works fine for type user / Team.

Steps
1) Select a entity of type organization
2) Select a record of that type
3) select a user
4) Press the Retrieve rights button

Expected
Get the indication for each priviliges type by the green/red indication

Actual
Get an error message, see attachment
![2017-01-20 15_50_16-error](https://cloud.githubusercontent.com/assets/1481424/22153575/313ca052-df28-11e6-8bb5-432168bd7bf3.png)

**Comment by MscrmTools** [comment]
It is a limitation from the SDK.

I can add a message that indicates that it is not supported if needed
